# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c5527383c0b4c07b8b83d3ff6d30e6c9eff1ac1a3fde0a75800a496648863d2eb17542d6df8ef289da99abc8e64fc242c1afe3525689d137c9185080275a197

test:
  secret_key_base: 3fad437223e1cfd3990e54a9860dd3a119ec674d82bf8e1ced02ddc96b8d59457b871c611514a12123e0d188898fbb4be782f0c9560c72bc204db175143962e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
